# Generated by Django 3.0.7 on 2020-06-29 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaddocuments', '0003_auto_20200628_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocuments',
            name='graduate',
            field=models.FileField(upload_to='media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])]),
        ),
        migrations.AlterField(
            model_name='uploaddocuments',
            name='photo',
            field=models.ImageField(height_field=50, upload_to='media/%Y/%m/%d/', width_field=50),
        ),
        migrations.AlterField(
            model_name='uploaddocuments',
            name='ten_x',
            field=models.FileField(upload_to='media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='uploaddocuments',
            name='twelve_xii',
            field=models.FileField(upload_to='media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
