# Generated by Django 3.0.7 on 2020-06-30 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaddocuments', '0004_auto_20200629_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocuments',
            name='photo',
            field=models.FileField(upload_to='media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
