# Generated by Django 3.0.7 on 2020-07-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaddocuments', '0007_auto_20200701_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocuments',
            name='photo',
            field=models.ImageField(height_field=45, upload_to='media/%Y/%m/%d/', width_field=35),
        ),
    ]
