# Generated by Django 3.1 on 2020-08-19 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaddocuments', '0009_auto_20200701_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocuments',
            name='ten_x',
            field=models.FileField(null=True, upload_to='media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='uploaddocuments',
            name='twelve_xii',
            field=models.FileField(null=True, upload_to='media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
