# Generated by Django 3.0.7 on 2020-06-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extraactivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_details', models.TextField()),
                ('twelve_details', models.TextField()),
                ('graduation_details', models.TextField()),
            ],
        ),
    ]
