# Generated by Django 3.0.7 on 2020-06-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraactivity', '0002_auto_20200627_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraactivity',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
