# Generated by Django 3.0.7 on 2020-06-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_x', models.IntegerField()),
                ('board_x', models.CharField(max_length=50)),
                ('school_x', models.CharField(max_length=50)),
                ('percentage_x', models.IntegerField()),
                ('roll_xii', models.IntegerField()),
                ('board_xii', models.CharField(max_length=50)),
                ('school_xii', models.CharField(max_length=50)),
                ('percentage_xii', models.IntegerField()),
                ('degree_name', models.CharField(max_length=20)),
                ('univ_name', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=50)),
                ('univ_roll', models.IntegerField()),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
