# Generated by Django 3.0.7 on 2020-06-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
