# Generated by Django 3.0.7 on 2020-07-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='middle_name',
        ),
    ]
